use mydatabase;
SELECT * FROM eda_output;

# total revenue generated by male and female customer
select gender, sum(purchase_amount) as revenue
from eda_output
group by gender;

# customer used a discount but still spent more than the average purchase amount
select customer_id, purchase_amount
from eda_output
where promo_code_used = "Yes" and purchase_amount >= (select avg(purchase_amount) from eda_output);

# top 5 product with the highest average review rating
select item_purchased, round(avg(review_rating),2) as "avg_rating"
from eda_output
group by item_purchased
order by avg(review_rating) desc
limit 5;

# compare the avg purchase amount between standard and express shipping
select shipping_type , round(avg(purchase_amount),2)
from eda_output
where shipping_type in ('Standard','Express')
group by shipping_type;

# do subscribed customer spend more? compare avg spend and total revenue bw subscriber and non-subscriber
select subscription_status, count(customer_id) as total_customer,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from eda_output
group by subscription_status
order by total_revenue, avg_spend desc;

# 5 product have the highest %age of purchase with discount applied
select item_purchased ,
round(100 * sum(case when promo_code_used="Yes" then 1 else 0 end)/count(*),2) as discount_rate
from eda_output
group by item_purchased
order by discount_rate desc
limit 5;

# segment customers into new, returning, and loyal based on their total number of previous purchase, and show the count
-- of each segment.
WITH cte AS (
 SELECT customer_id,
        previous_purchases,
        CASE 
           WHEN previous_purchases = 1 THEN 'New'
           WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
           ELSE 'Loyal'
        END AS customer_segment
 FROM eda_output
)

SELECT customer_segment, count(*) as no_of_customer
FROM cte
group by customer_segment;

# what are the top 3 most purchased products within each products
with item_count as (
select category, item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from eda_output 
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_count
where item_rank <= 3;

# are customer who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_customer
from eda_output
where previous_purchases > 5
group by subscription_status;

# what is the revenue contribution of each age group?
select age_group, sum(purchase_amount) as revenue
from eda_output
group by age_group
order by sum(purchase_amount) desc;










